data:
  data_dir: /media/dhruv/a7519aee-b272-44ae-a117-1f1ea1796db6/2024/arcmg/data/pendulum_lqr/pendulum_lqr5k/pendulum_lqr5k
  seq_len: 500

model:
  distillation_model_path: checkpoints/distillation_model.pth
  transformer_model_path: checkpoints/transformer_model.pth

training:
  learning_rate: 0.001
  save_path: checkpoints/combined_model.pth