data:
  data_dir: /media/dhruv/a7519aee-b272-44ae-a117-1f1ea1796db6/2024/arcmg/data/pendulum_lqr/pendulum_lqr5k/pendulum_lqr5k
  seq_len: 500
  mask_ratio_range: [0.0, 1.0]

model:
  input_dim: 2
  d_model: 64
  nhead: 1
  num_layers: 3
  dim_feedforward: 256
  use_positional_encoding: false

training:
  num_epochs: 20
  batch_size: 128
  learning_rate: 0.0001
  save_path: checkpoints/transformer_model.pth